[package]
name = "image_palette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
image = "0.23"
palette_extract = "0.1.0"
reqwest = {version = "0.11.14", features = ["blocking"]}
